apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ONS-APIs
  description: Coleção de todas as APIs disponíveis no ONS.
spec:
  targets:
    - https://github.com/wallacecnhaug/icustom/blob/master/api-GDESSEM.yaml
    - https://github.com/wallacecnhaug/icustom/blob/master/api-PDP.yaml
