apiVersion: v1
kind: API
metadata:
  name: GDESSEM
  description: API - GDESSEM
  tags:
    - gdessem
    - rest
 
spec:
  type: OpenAPI
  lifecycle: Produção
  owner: ONS-Arquitetura-GDESSEM
  definition:
    $text: https://github.com/wallacecnhaug/icustom/blob/master/openapi.yaml